services:
  - type: web
    name: my-rails-tutorial
    env: docker
    plan: free  # 無料プランを利用する場合
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    buildCommand: ./bin/render-build.sh  # カスタムビルドコマンドを指定
    startCommand: docker-compose up  # アプリケーションの起動コマンド
    envVars:
      - key: DATABASE_URL
        sync: false  # Renderの設定画面でデータベースURLを入力
      - key: PORT
        value: 3003
