default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5

development:
  <<: *default
  database: tutorial

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  # HerokuではDATABASE_URL環境変数が自動的に設定されるため、以下のようにします。
  url: <%= ENV['DATABASE_URL'] %>


# default: &default
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see Rails configuration guide
#   # https://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   host: db
#   username: user
#   password: password

# development:
#   <<: *default
#   database: tutorial


# test:
#   <<: *default
#   database: myapp_test


# production:
#   <<: *default
#   database: myapp_production
#   username: myapp
#   password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
